### ISSUE TITLE
Python version requirement

### ISSUE THREAD

**Issue by remyeltorro** [chandrasekarnarayana/Modeling-GUI#1]
Hello @chandrasekarnarayana,

I tried to install the GUI with a conda environment and a python version<3.9,

I obtained the following error,

```bash
ERROR: Package 'modeling-gui' requires a different Python: 3.8.10 not in '>=3.9'
```
I'll try again with Python 3.9 as per the requirement (maybe update the README to specify that it does not work for python versions below 3.9),

Cheers

**Comment by chandrasekarnarayana** [comment]
Hello @remyeltorro 
Thank you very much for the feedback.
Yes, the package was developed using python 3.9 and has been set as a requirement.
The package is in it initial stages of development, your contributions are valuable.
`pip install modeling-gui`
The above command can also be used for installation.

Thank you

**Comment by remyeltorro** [comment]
> Hello @remyeltorro 
> Thank you very much for the feedback.
> Yes, the package was developed using python 3.9 and has been set as a requirement.
> The package is in it initial stages of development, your contributions are valuable.
> `pip install modeling-gui`
> The above command can also be used for installation.
> 
> Thank you

The README says otherwise, please update it 😁
