### ISSUE TITLE
Launching GUI

### ISSUE THREAD

**Issue by remyeltorro** [chandrasekarnarayana/Modeling-GUI#2]
Hello @chandrasekarnarayana,

I couldn't use the `run_modeling_gui` shortcut to open the UI, I got the following error:

``` bash
AttributeError: module 'modeling_gui.main' has no attribute 'main'
```

I managed to open it by typing `python modeling_gui/main.py`,

I suggest you rename `main.py` into `__main__.py` and use `python -m modeling_gui` to launch it as a package and have a working shortcut to the GUI (you may have to do some changes in the `setup.py`)

The GUI opens to a blank / empty window, is that intended?

![image](https://github.com/user-attachments/assets/c58db7d7-18c0-449f-8c30-fafaa4bacf0a)

Cheers

**Comment by chandrasekarnarayana** [comment]
Hello @remyeltorro ,

Thank you for reporting this bug.

We've addressed the issue with the main GUI. We're currently working on improving the data connection, error handling, and the visualization of model results.

You can now launch the GUI either by running `python -m modeling_gui.main` or using `run_modeling_gui` after installation.

Your feedback and contributions are greatly appreciated!

Best regards.
